### ISSUE TITLE
Reset EVERYONES level

### ISSUE THREAD

**Issue by Matesker** [vrondakis/Leveling-System#24]
How do I reset everyones level? and if its Mysql how do I connect to it?

**Comment by vrondakis** [comment]
Remove everything from the darkrp_levels table

You can run "DELETE FROM darkrp_levels WHERE 1"

**Comment by Matesker** [comment]
Thank you, after that do I just basically add the default darkrp_levels?

**Comment by vrondakis** [comment]
It'll be created automatically

**Comment by Matesker** [comment]
And where were the darkrp_levels tables located?

**Comment by vrondakis** [comment]
Errr? In whatever database you're using
