### ISSUE TITLE
Job level falire? PLEASE HELP!!

### ISSUE THREAD

**Issue by BoscarCakes** [vrondakis/Leveling-System#26]
I put the "level" command in my job. (Here it is:)
![capture](https://cloud.githubusercontent.com/assets/12865523/8680664/c1b7eefe-2a5a-11e5-8479-eef56e9b502b.JPG)

And then a lua error appears saying that my line was supposed to be closed before the "category" on line 36.

PLEASE HELP, IT WILL BE APPRECIATED!

**Comment by LeCoffee** [comment]
You're missing a comma.

**Comment by BoscarCakes** [comment]
THANKS!!

**Comment by vrondakis** [comment]
Nice one murt!
