### ISSUE TITLE
The addon isnt working, PLEASE HELP!

### ISSUE THREAD

**Issue by BoscarCakes** [vrondakis/Leveling-System#27]
I put the addon in E:/GMOD/garrysmod and the XP bar and the entire addon is not working. Please HELP!!!
![capture](https://cloud.githubusercontent.com/assets/12865523/8681492/99ee8cac-2a5f-11e5-9e8e-ab7ca974ef99.JPG)

**Comment by vrondakis** [comment]
No addons are installed by putting a folder into your garrysmod folder

Read the setup instructions
