### ISSUE TITLE
Im having a problem i have 2-3 lau errors

### ISSUE THREAD

**Issue by Darkpie109** [vrondakis/Leveling-System#30]
the lua error is like this

There are 2 Lua problems!
	Please check your console for more information!
[ERROR] A runtime error has occurred in "addons/levels/lua/darkrp_modules/levels/sv_data.lua" on line 28.
The best help I can give you is this:

Warning! DarkRPVar 'xp' wasn't registered!
 		Please contact the author of the DarkRP Addon to fix this.
 		Until this is fixed you don't need to worry about anything. Everything will keep working.
 		It's just that registering DarkRPVars would make DarkRP faster.

Hints:
	- No hints, sorry.

The responsibility for this error lies with (the authors of) one (or more) of these files:
	1. addons/levels/lua/darkrp_modules/levels/sv_data.lua on line 28
	2. addons/levels/lua/darkrp_modules/levels/sv_data.lua on line 14
	3. gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua on line 291
	4. addons/levels/lua/darkrp_modules/levels/sv_data.lua on line 14
	5. addons/levels/lua/darkrp_modules/levels/sv_data.lua on line 23
	6. addons/levels/lua/darkrp_modules/levels/sh_core.lua on line 200
	7. addons/ulib/lua/ulib/shared/hook.lua on line 110
------- End of Simplerr error -------

[ERROR] A runtime error has occurred in "addons/levels/lua/darkrp_modules/levels/sv_data.lua" on line 29.
The best help I can give you is this:

Warning! DarkRPVar 'level' wasn't registered!
 		Please contact the author of the DarkRP Addon to fix this.
 		Until this is fixed you don't need to worry about anything. Everything will keep working.
 		It's just that registering DarkRPVars would make DarkRP faster.

Hints:
	- No hints, sorry.

The responsibility for this error lies with (the authors of) one (or more) of these files:
	1. addons/levels/lua/darkrp_modules/levels/sv_data.lua on line 29
	2. addons/levels/lua/darkrp_modules/levels/sv_data.lua on line 14
	3. gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua on line 291
	4. addons/levels/lua/darkrp_modules/levels/sv_data.lua on line 14
	5. addons/levels/lua/darkrp_modules/levels/sv_data.lua on line 23
	6. addons/levels/lua/darkrp_modules/levels/sh_core.lua on line 200
	7. addons/ulib/lua/ulib/shared/hook.lua on line 110
------- End of Simplerr error -------

**Comment by vrondakis** [comment]
You don't have the github version installed
