### ISSUE TITLE
Printer Issues

### ISSUE THREAD

**Issue by ZackMington** [vrondakis/Leveling-System#31]
Sometimes, a server of mine crashes and It seems like that the printers are number 1 source of it. Here's a picture that displays what the error(s) are.
http://i.imgur.com/WPpPPh3.png

**Comment by vrondakis** [comment]
Definitely not causing crashes but I'll look into it regardless

**Comment by ZackMington** [comment]
Well, do you know what can cause this? Or have you solved it yet?

**Comment by vrondakis** [comment]
Again, this addon is definitely not causing actual crashes but that error has been fixed in the latest update. Enjoy!
