### ISSUE TITLE
the xp gain thing is broken

### ISSUE THREAD

**Issue by bor2571** [vrondakis/Leveling-System#32]
I used the workshop version and got this error

[ERROR] A runtime error has occurred in "lua/darkrp_modules/levels/sv_data.lua" on line 28.
The best help I can give you is this:

Warning! DarkRPVar 'xp' wasn't registered!
 		Please contact the author of the DarkRP Addon to fix this.
 		Until this is fixed you don't need to worry about anything. Everything will keep working.
 		It's just that registering DarkRPVars would make DarkRP faster.

Hints:
	- No hints, sorry.

The responsibility for this error lies with (the authors of) one (or more) of these files:
	1. lua/darkrp_modules/levels/sv_data.lua on line 28
	2. lua/darkrp_modules/levels/sv_data.lua on line 14
	3. gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua on line 300
	4. lua/darkrp_modules/levels/sv_data.lua on line 14
	5. lua/darkrp_modules/levels/sv_data.lua on line 23
	6. lua/darkrp_modules/levels/sh_core.lua on line 200
	7. addons/ulib/lua/ulib/shared/hook.lua on line 179
------- End of Simplerr error -------

[ERROR] A runtime error has occurred in "lua/darkrp_modules/levels/sv_data.lua" on line 29.
The best help I can give you is this:

Warning! DarkRPVar 'level' wasn't registered!
 		Please contact the author of the DarkRP Addon to fix this.
 		Until this is fixed you don't need to worry about anything. Everything will keep working.
 		It's just that registering DarkRPVars would make DarkRP faster.

Hints:
	- No hints, sorry.

The responsibility for this error lies with (the authors of) one (or more) of these files:
	1. lua/darkrp_modules/levels/sv_data.lua on line 29
	2. lua/darkrp_modules/levels/sv_data.lua on line 14
	3. gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua on line 300
	4. lua/darkrp_modules/levels/sv_data.lua on line 14
	5. lua/darkrp_modules/levels/sv_data.lua on line 23
	6. lua/darkrp_modules/levels/sh_core.lua on line 200
	7. addons/ulib/lua/ulib/shared/hook.lua on line 179
------- End of Simplerr error -------

**Comment by vrondakis** [comment]
Then use the GitHub version, duh
