### ISSUE TITLE
XP Books

### ISSUE THREAD

**Issue by XxL3G1TS4VAG3xX** [vrondakis/Leveling-System#34]
Hello Author,

When I was trying to create XP Books all i got was nothing but errors... I used the .lua file for the book as well but nothing showd up in the entities list. So i used the darkrp modification and thats where the error occurred so I just stopped. How does one setup XP Books?

**Comment by vrondakis** [comment]
Next time you post an issue be sure to include everything including the code you used an what the errors were. It's impossible to help when you're that vague

But..
Books were removed months ago so there's your problem
