### ISSUE TITLE
problem with f4

### ISSUE THREAD

**Issue by ZWigleg** [vrondakis/Leveling-System#35]
Every time I installed the mod when I go to the game I do not see the jobs or the shipments. I see nothing in F4, the install it was good. Help

**Comment by vrondakis** [comment]
Post your console errors

**Comment by ZWigleg** [comment]
In the server console? Or game console?
PD: Sorry for wasting time

**Comment by vrondakis** [comment]
The one that has errors in it

**Comment by ZWigleg** [comment]
The problem that the jobs did not appears I was under. Now what happens to me is that I can not buy the printers

**Comment by ZWigleg** [comment]
The problem that the jobs did not appears I was under. Now what happens to me is that I can not buy the printers

**Comment by vrondakis** [comment]
There are definitely console errors and I can't help unless you show me them

**Comment by ZWigleg** [comment]
[ERROR] addons/darkrpmodification/lua/darkrp_customthings/jobs.lua:47: '}' expected (to close '{' at line 34) near 'maps'
  1. unknown - addons/darkrpmodification/lua/darkrp_customthings/jobs.lua:0


[DarkRP] A runtime error has occurred in "addons/darkrpmodification/lua/darkrp_modules/levels/sh_config.lua" on line 170.
The best help I can give you is this:

Corrupt entity: Regular Printer!
This entity does not have a unique command.

Hints:
	- There must be some other end that has the same thing for 'cmd'.
	- Fix this by changing the 'cmd' field of your entity to something else.

The responsibility for this error lies with (the authors of) one (or more) of these files:
	1. addons/darkrpmodification/lua/darkrp_modules/levels/sh_config.lua on line 170
	2. addons/ulib/lua/ulib/shared/hook.lua on line 179
	3. gamemodes/darkrp/gamemode/libraries/modificationloader.lua on line 149
	4. gamemodes/darkrp/gamemode/cl_init.lua on line 48
------- End of Simplerr error -------

  1. error - [C]:-1
   2. unknown - gamemodes/darkrp/gamemode/libraries/simplerr.lua:467
    3. error - gamemodes/darkrp/gamemode/libraries/fn.lua:80
     4. createEntity - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:834
      5. fn - addons/darkrpmodification/lua/darkrp_modules/levels/sh_config.lua:170
       6. Call - addons/ulib/lua/ulib/shared/hook.lua:179
        7. Call - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:149
         8. unknown - gamemodes/darkrp/gamemode/cl_init.lua:48

Couldn't Load Init Script: 'darkrp/gamemode/cl_init.lua'

**Comment by vrondakis** [comment]
You've made a syntax error in your config file, it's not my fault
