### ISSUE TITLE
All jobs turn green

### ISSUE THREAD

**Issue by deadlyshot02** [vrondakis/Leveling-System#36]
The addon works flawlessly, however, I noticed for some reason, it makes all jobs in the F4 menu green (or the Citizen's default color), I already tested it without the addon and this doesn't happen, so it's definitely this addon what's causing it. I'm running DarkRP 2.6.1, and it shows no lua/script errors when opening the server, when joining it, or when pressing F4, so I have no clue of what the cause is. Please take a look at this.

**Comment by vrondakis** [comment]
Nice
