### ISSUE TITLE
Player disconnect

### ISSUE THREAD

**Issue by SubjectAlpha** [vrondakis/Leveling-System#37]
When a player disconnects, their printer stays. I added this to try and fix that, but it hasn't worked. I don't know if something is conflicting or what, I just need some help with this one.

function ENT:PlayerDisconnect()
	self:Destruct()
	self:Remove()
end
hook.Add("PlayerDisconnected", "OnPlayerDisconnect1234", PlayerDisconnect)

**Comment by vrondakis** [comment]
GM.Config.removeondisconnect ?

**Comment by SubjectAlpha** [comment]
My bad, I wasn't using that version of DarkRP that had that option. I updated and its fine now. Thanks.
