### ISSUE TITLE
I cant get rid of printers

### ISSUE THREAD

**Issue by Squirtlicious** [vrondakis/Leveling-System#39]
I can't get rid of the printers from the entities menu in f4, how would I go about removing them?

**Comment by vrondakis** [comment]
Have you removed them from the config?

On Wed, Feb 10, 2016 at 1:19 PM, Squirtlicious <notifications@github.com>
wrote:

> I can't get rid of the printers from the entities menu in f4, how would I
> go about removing them?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vrondakis/Leveling-System/issues/39>.
>



-- 
*Manolis Vrondakis*
http://manolisvrondakis.com/

**Comment by Squirtlicious** [comment]
Which one of them?

**Comment by vrondakis** [comment]
The one in this system

**Comment by Squirtlicious** [comment]
I'm sorry but I dont think I know which one you mean

**Comment by vrondakis** [comment]
Really?

**Comment by Squirtlicious** [comment]
Yes I do not know which one you mean, Do you mean the DarkRP one or one for your printers? Because I cant find one in your printers and I cant see your printers in any of the normal Darkrp configs

**Comment by vrondakis** [comment]
You cannot be helped

**Comment by Squirtlicious** [comment]
I just want to know which config you're talking about

**Comment by vrondakis** [comment]
The config file in this system read the readme!

**Comment by Squirtlicious** [comment]
Ah, thank you very much.
