### ISSUE TITLE
Linux not working Mysql

### ISSUE THREAD

**Issue by dok441** [vrondakis/Leveling-System#40]
gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:264: Lost connection t                                                                                                                                                             o MySQL server during query (SELECT level,xp FROM darkrp_levels WHERE uid = 
"4005534345";)

It always writes and does not use data recorded in mysql, linux debian 7. Used the latest darkrp

**Comment by vrondakis** [comment]
This uses DarkRP's mysqlite API, it's nothing to do with this. Probably a
bad connection between your game server and MySQL server
