### ISSUE TITLE
Lag mysql system darkrp

### ISSUE THREAD

**Issue by dok441** [vrondakis/Leveling-System#41]
Hello, I have a problem with your work, because of her terrible lags, lags occur because of the connection with mysql, the mysql load is very high, I checked on the script https://github.com/oubliette32/DBugR I niznayu what is the reason, but unfortunately, the whole process chews and play 6-10 hours is no longer possible, and the next day, eats half of the CPU hard if there is no lag. Can modify? Put it away I fell much load and no more problems. But your work is very good and I like it I wish I had.

**Comment by vrondakis** [comment]
Are you sure this is my system? (Because it isn't)

It uses DarkRP's MySQL wrapper and only queries when XP is saved or a player joins. Exactly the same way money is saved / retrieved

**Comment by vrondakis** [comment]
Try using tmysql4 instead of mysqloo

**Comment by dok441** [comment]
I'm not sure how tmysql4 to install, didn't work with him at all.

**Comment by vrondakis** [comment]
Make this in the DarkRP GitHub
