### ISSUE TITLE
[suggestion] Exp module

### ISSUE THREAD

**Issue by matiasg90** [vrondakis/Leveling-System#44]
possible, add the amount of exp to Kill a player?
something like:

LevelSystemConfiguration.KillModule = False  //Only module kill money
LevelSystemConfiguration.Friendly = true
LevelSystemConfiguration.TakeAwayMoneyAmount = 100

LevelSystemConfiguration.Expmodule = true //Only exp kill
LevelSystemConfiguration.Expammount = 150 //Amount of exp to kill.

**Comment by vrondakis** [comment]
It's calculated depending on the difference between the victims and attackers level. Doing it like this would give low level players crazy amounts of XP or wouldn't give high level players enough
