### ISSUE TITLE
upgrade to steamid64

### ISSUE THREAD

**Issue by matiasg90** [vrondakis/Leveling-System#47]
http://forum.darkrp.com/threads/darkrp-2-7-0.7547/

For the technical minded, this is the specific commit that breaks backwards compatibility:
https://github.com/FPtje/DarkRP/commit/61fa0c28c961aa1391dde1147d4f51c5dffa75a4

**Comment by matiasg90** [comment]
?

**Comment by vrondakis** [comment]
exactly
