### ISSUE TITLE
Editing HUD "level"

### ISSUE THREAD

**Issue by BlitherLlama** [vrondakis/Leveling-System#48]
How do I get the hud "level" to look like this http://i.imgur.com/t8nK19g.png
Mine currently looks like this: http://i.imgur.com/CuEAyp1.jpg
From what I can see, it cant be edited through the use of the X/Y coordinates, so I was wondering if there was an option somewhere to change that.

**Comment by AMD-NICK** [comment]
looks good

**Comment by BlitherLlama** [comment]
What, I'm looking to make mine look like the one in the first image, with the "Level: X" being on the top in the blue bar.
