### ISSUE TITLE
Custom Checks

### ISSUE THREAD

**Issue by Survivor21** [vrondakis/Leveling-System#50]
Currently I am trying to make a custom check to see if the player is a certain level, and if they are they can use that entity (not spawn it, interact with it)

I've tried it with ply:hasLevel ply:getLevel Level = , (With different capitalization)

Doesnt work with that, the entity with that, doesnt show up.

I am doing it with

if (custom check for level/plain level) then

(entity)

end

**Comment by vrondakis** [comment]
Hello mate I'm fucked

Baggage baguettes baguette baguette bagueyyebfuck off

If you want to get a players level you can use

ply:getDarkRPVar('level')

Where ply is the player

Therefore if you want a custom check on an object you can use

function(ply) return ply:getDarkRPVar('level') > 10 end

You can just use the level = 10 parameter

I don't really fucking know

**Comment by Survivor21** [comment]
function ENT:Use(a,c)
	
	if function(ply) return ply:getDarkRPVar('level') < 6 end else print ("Wrong Year!") then
	self:Remove()
	self:SetUseType( SIMPLE_USE )
	net.Start("server_say_spell_add")
				net.WriteString("Avada Kedavra")
				net.WriteEntity(c)
	net.Send(c)
	end 
end


Tried using that, but still anyone can interact with it. Just using level = 6 makes the entity not even show up :P Any more ideas, 

Thanks for the help so far !
