### ISSUE TITLE
Disable the level bar above your head

### ISSUE THREAD

**Issue by Webber3110** [vrondakis/Leveling-System#52]
How can you disable this "level" bar above your head? Its annoying, please help.

**Comment by vrondakis** [comment]
Do you mean the level text that appears when you look at players or the level bar at the top of the screen? There isn't a bar at the top of your head.. If you mean the text I added a config for it in the latest version: LevelSystemConfiguration.DisplayLevel

**Comment by Webber3110** [comment]
I mean the text that is about your own head.

2016-07-15 14:24 GMT+02:00 Manolis Vrondakis <notifications@github.com>:

**Comment by vrondakis** [comment]
There is no text above your own head

**Comment by Webber3110** [comment]
I deinstalled and reinstalled it. There is something that is saying "level XY" above my head and above the head of other players while im looking at them. How can i disable it?

**Comment by vrondakis** [comment]
config file
