### ISSUE TITLE
Im stumped here 

### ISSUE THREAD

**Issue by loaf2001** [vrondakis/Leveling-System#53]
[ERROR] addons/ulx/lua/ulx/modules/sh/levels.lua:4: attempt to call method 'addXP' (a nil value)
1. call - addons/ulx/lua/ulx/modules/sh/levels.lua:4
   1. __fn - addons/ulib/lua/ulib/shared/commands.lua:943
   2. unknown - addons/ulib/lua/ulib/shared/commands.lua:1296
      1. Run - lua/includes/modules/concommand.lua:54
      2. unknown - addons/ulib/lua/ulib/shared/commands.lua:1311
      3. unknown - lua/includes/modules/concommand.lua:54

i get this error

**Comment by AMD-NICK** [comment]
(V)_(;,,;)_(V)

**Comment by vrondakis** [comment]
Do you get errors on startup?
