### ISSUE TITLE
Pink XP Hud

### ISSUE THREAD

**Issue by mexarcz** [vrondakis/Leveling-System#62]
Screenshot : https://ctrlv.cz/HajD
How i can fix that?

**Comment by AMD-NICK** [comment]
Just delete addon folder

**Comment by mexarcz** [comment]
Server or my folder with addons?

**Comment by vrondakis** [comment]
Remove garrysmod folder

**Comment by paxoboy** [comment]
He provides little or no support dont bother and get another addon
