### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by paxoboy** [vrondakis/Leveling-System#63]
is it possible to have a rank line under it where it could say for example Rank: Private if the character is the level of 5?

**Comment by vrondakis** [comment]
local levels = {"Private", "General", "Whatever"}
Local levelStr = levels[playerLevel] or "Unknown"

On 19 Apr 2017 10:58 am, "paxoboy" <notifications@github.com> wrote:

is it possible to have a rank line under it where it could say for example
Rank: Private if the character is the level of 5?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/vrondakis/Leveling-System/issues/63>, or mute the thread

**Comment by paxoboy** [comment]
sorry could you explain it a bit more thanks - still learning lua

**Comment by vrondakis** [comment]
local levels = {"Private", "General", "Whatever"}
local levelStr = "Rank: "..(levels[LocalPlayer():getDarkRPVar('level')] or
"Unknown")

**Comment by paxoboy** [comment]
do i just add that in or?

**Comment by vrondakis** [comment]
Are u learning Lua or do u know nothing lol

**Comment by paxoboy** [comment]
Well it would help if you explained yourself

**Comment by vrondakis** [comment]
Put levelStr in substitute of "Level:"..ect

**Comment by paxoboy** [comment]
ok thanks :)

**Comment by paxoboy** [comment]
ok so i have added it in properly ect but it still saids 0 instead of the rank ill copy and paste it into what i have done

`// Love Manolis Vrondakis. @vrondakis

surface.CreateFont( "HeadBar", { // XP Bar font
	 font = "Tahoma",
	 size = 13,
	 weight = 500,
	 blursize = 0,
	 scanlines = 0,
} )

surface.CreateFont("LevelPrompt", { // Level prompt font
	font = "Francois One",
	size = 70,
	weight = 500,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
}) 

local levels = {"Private", "General", "Whatever"}
-- local levelStr = "Rank: "..(levels[LocalPlayer():getDarkRPVar('level')] or"Unknown")  WAS A NOTE

// I hate this fucking DrawDisplay function. Eurgh.
local function DrawDisplay()
local shouldDraw, players = hook.Call("HUDShouldDraw", GAMEMODE, "DarkRP_EntityDisplay")
	if shouldDraw == false then return end
	local shootPos = LocalPlayer():GetShootPos()
	local aimVec = LocalPlayer():GetAimVector()
	if(LevelSystemConfiguration.DisplayLevel) then
		for k, ply in pairs(players or player.GetAll()) do
			if not ply:Alive() then continue end
			local hisPos = ply:GetShootPos()
			if GAMEMODE.Config.globalshow and ply ~= localplayer then
					local pos = ply:EyePos()
					pos.z = pos.z + 10 -- The position we want is a bit above the position of the eyes
					pos = pos:ToScreen()
					pos.y = pos.y-20
					draw.DrawText('Level: '..(ply:getDarkRPVar('LevelStr') or 0), "DarkRPHUD2", pos.x+1, pos.y -56, Color(0,0,0,255), 1)
					draw.DrawText('Level: '..(ply:getDarkRPVar('LevelStr') or 0), "DarkRPHUD2", pos.x, pos.y -55, Color(255,255,255,200), 1)
			elseif not GAMEMODE.Config.globalshow and hisPos:Distance(shootPos) < 250 then
				local pos = hisPos - shootPos
				local unitPos = pos:GetNormalized()
	
					local trace = util.QuickTrace(shootPos, pos, localplayer)
					if trace.Hit and trace.Entity ~= ply then return end
						local pos = ply:EyePos()
						pos.z = pos.z + 10 -- The position we want is a bit above the position of the eyes
						pos = pos:ToScreen()
						pos.y = pos.y-20
						draw.DrawText('Level: '..(ply:getDarkRPVar('LevelStr') or 0), "DarkRPHUD2", pos.x, pos.y -58, Color(0,0,0,255), 1)
						draw.DrawText('Level: '..(ply:getDarkRPVar('LevelStr') or 0), "DarkRPHUD2", pos.x+1, pos.y -57, Color(255,255,255,200), 1)
			end
		end
	end
 
	local tr = LocalPlayer():GetEyeTrace()`

**Comment by paxoboy** [comment]
it may be me just being dumb rip

**Comment by paxoboy** [comment]
nvm i fixed it thanks for the help

**Comment by paxoboy** [comment]
Update: so i have got it to work ect but when i set the level of myself or another player it updates everything on the text idk why heres the code



`// Love Manolis Vrondakis. @vrondakis

surface.CreateFont( "HeadBar", { // XP Bar font
	 font = "Tahoma",
	 size = 13,
	 weight = 500,
	 blursize = 0,
	 scanlines = 0,
} )

surface.CreateFont("LevelPrompt", { // Level prompt font
	font = "Francois One",
	size = 70,
	weight = 500,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
}) 

local levels = {"Recruit", "General", "Whatever"}

// I hate this fucking DrawDisplay function. Eurgh.
local function DrawDisplay()
local shouldDraw, players = hook.Call("HUDShouldDraw", GAMEMODE, "DarkRP_EntityDisplay")
	if shouldDraw == false then return end
	local shootPos = LocalPlayer():GetShootPos()
	local aimVec = LocalPlayer():GetAimVector()
	if(LevelSystemConfiguration.DisplayLevel) then
		for k, ply in pairs(players or player.GetAll()) do
			if not ply:Alive() then continue end
			local hisPos = ply:GetShootPos()
			if GAMEMODE.Config.globalshow and ply ~= localplayer then
					local pos = ply:EyePos()
					pos.z = pos.z + 10 -- The position we want is a bit above the position of the eyes
					pos = pos:ToScreen()
					pos.y = pos.y-20
					draw.DrawText("Rank: "..(levels[LocalPlayer():getDarkRPVar('level')] or"Unknown"), "DarkRPHUD2", pos.x+1, pos.y -56, Color(0,0,0,255), 1)
					draw.DrawText("Rank: "..(levels[LocalPlayer():getDarkRPVar('level')] or"Unknown"), "DarkRPHUD2", pos.x, pos.y -55, Color(255,255,255,200), 1)
			elseif not GAMEMODE.Config.globalshow and hisPos:Distance(shootPos) < 250 then
				local pos = hisPos - shootPos
				local unitPos = pos:GetNormalized()
	
					local trace = util.QuickTrace(shootPos, pos, localplayer)
					if trace.Hit and trace.Entity ~= ply then return end
						local pos = ply:EyePos()
						pos.z = pos.z + 10 -- The position we want is a bit above the position of the eyes
						pos = pos:ToScreen()
						pos.y = pos.y-20
						draw.DrawText("Rank: "..(levels[LocalPlayer():getDarkRPVar('level')] or"Unknown"), "DarkRPHUD2", pos.x, pos.y -58, Color(0,0,0,255), 1)
						draw.DrawText("Rank: "..(levels[LocalPlayer():getDarkRPVar('level')] or"Unknown"), "DarkRPHUD2", pos.x+1, pos.y -57, Color(255,255,255,200), 1)
						
			end
		end
	end
 
	local tr = LocalPlayer():GetEyeTrace()

end
local OldXP = 0
local xp_bar = Material("vrondakis/xp_bar.png","noclamp smooth")
local function HUDPaint()
	if not LevelSystemConfiguration then return end
	if not LevelSystemConfiguration.EnableHUD then return end
	local PlayerLevel = LocalPlayer():getDarkRPVar('level')
	local PlayerXP = LocalPlayer():getDarkRPVar('xp')
	
	// Draw the XP Bar
	local percent = ((PlayerXP or 0)/(((10+(((PlayerLevel or 1)*((PlayerLevel or 1)+1)*90))))*LevelSystemConfiguration.XPMult)) // Gets the accurate level up percentage
	
	local drawXP = Lerp(8*FrameTime(),OldXP,percent)
	OldXP = drawXP
	local percent2 = percent*100
	percent2 = math.Round(percent2)
	percent2 = math.Clamp(percent2, 0, 99) //Make sure it doesn't round past 100%

	surface.SetDrawColor(0,0,0,200)
	surface.DrawRect(ScrW()/2-300,0,580,25)

	// Draw the XP Bar before the texture
	surface.SetDrawColor(LevelSystemConfiguration.LevelBarColor[1],LevelSystemConfiguration.LevelBarColor[2],LevelSystemConfiguration.LevelBarColor[3],255)
	surface.DrawRect(ScrW()/2-300,0,580*drawXP,25)

	//Render the texture
	surface.SetMaterial(xp_bar)
	surface.SetDrawColor(255,255,255,255)
	surface.DrawTexturedRect( ScrW()/2-371, 0,  742,46)

	// Render the text
	draw.DrawText('Level '..(LocalPlayer():getDarkRPVar('level') or 0)..' - '..percent2 ..'%', "HeadBar", ScrW()/2,7,(LevelSystemConfiguration.XPTextColor or Color(255,255,255,255)), TEXT_ALIGN_CENTER, TEXT_ALIGN_CENTER)

	DrawDisplay()
end
hook.Add("HUDPaint", "manolis:MVLevels:HUDPaintA", HUDPaint) // IS THAT UNIQUE ENOUGH FOR YOU, FUCKING GMOD HOOKING BULLSHIT.


`

**Comment by vrondakis** [comment]
code

**Comment by vrondakis** [comment]
code
code
code
code
code
code
code
code
code
code
code
code
code
code
code
code
code
code
code
code
code
code
code
code
code
code
code
code
code

**Comment by paxoboy** [comment]
wtf was that just a spam of the word code then close the ticket nice support ( mostly none )

**Comment by vrondakis** [comment]
Pst "He provides little or no support dont bother and get another addon" definitely not telling you where to put that code now lol
