### ISSUE TITLE
How i change the Possition of The XP Bar?

### ISSUE THREAD

**Issue by MarioDelMonte** [vrondakis/Leveling-System#64]
I search alot dont know how to move that bar

**Comment by vrondakis** [comment]
Where do you wanna move it to...

**Comment by MarioDelMonte** [comment]
Down

**Comment by vrondakis** [comment]
Down to where

On 13 Jul 2017 10:52 am, "MarioDelMonte" <notifications@github.com> wrote:

Down

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/vrondakis/Leveling-System/issues/64#issuecomment-314955661>,
or mute the thread

**Comment by MarioDelMonte** [comment]
Like the Xp bar Move it down of the screen. Where are the Bullets, HP , etc

**Comment by MarioDelMonte** [comment]
Bottom Of the screen

**Comment by MarioDelMonte** [comment]
Emmm K

**Comment by vrondakis** [comment]
There is a config value for this now

**Comment by MarioDelMonte** [comment]
Thanks man :)
