### ISSUE TITLE
printer Exploding issue

### ISSUE THREAD

**Issue by BasonTaylor** [vrondakis/Leveling-System#69]
okay i have a map almost 90 % is props But When people destroy your printers they set the whole player-base and map on fire for 20 seconds or so. I was wondering if there is some way to combat this and make it so they don't set props on fire apon explosion or make it so there is a config option to disable it.

**Comment by vrondakis** [comment]
I doubt the printer exploding sets everyone on fire unless your map is only 20 units. Comment out lines 50-52, 55 and 115 to disable to fire
