### ISSUE TITLE
Request not important

### ISSUE THREAD

**Issue by BasonTaylor** [vrondakis/Leveling-System#70]
Is there a way to make some printers for ulx groups

**Comment by BasonTaylor** [comment]
customCheck = function(ply) return CLIENT or
        table.HasValue({"2", "1", "3", "4", "5", "6"}, ply:GetNWString("usergroup"))
    end,
    CustomCheckFailMsg = "ffdssfsdff.",
})

**Comment by vrondakis** [comment]
Printer.CustomCheck = function(ply) 
    ...
end
