### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Cocobor** [vrondakis/Leveling-System#77]
Help please!When starting, it gives an error

[ERROR] gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:893: attempt to index local 'cat' (a nil value)
1. mergeCategories - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:893
2. fn - gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua:906
3. Call - addons/ulib/lua/ulib/shared/hook.lua:109
4. Call - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:149
5. unknown - gamemodes/darkrp/gamemode/init.lua:107

Couldn't Load Init Script: 'darkrp/gamemode/init.lua'

**Comment by vrondakis** [comment]
Doesn't look like it has anything to do with this addon

**Comment by vrondakis** [comment]
Did you change anything in the config file? If so upload it

**Comment by Cocobor** [comment]
No, I did not change it, but just in case, I would download it.


Whoops! That unsubscribe link isn't valid for your account. =\
