### ISSUE TITLE
Adding weight for inventory system?

### ISSUE THREAD

**Issue by Ilunga1** [vrondakis/Leveling-System#81]
My inventory system requires a weight parameter to be added.

How would I go about doing this? in the install.txt the inv creator says Add weight parameter to every DarkRP.createShipment, DarkRP.createEntity, DarkRP.createFood.

So in the config for printers, is it 

Printer.weight = amount

or 

weight = amount

I'd appreciate any help, I need this fixed as players putting printers in their inv, then getting them out again puts them back to regular printers.

**Comment by Ilunga1** [comment]
Just tried both of these in a test server and none of them work. Any ideas?

**Comment by vrondakis** [comment]
Use Printer.pTable.weight
