### ISSUE TITLE
Ulx support

### ISSUE THREAD

**Issue by MpLLLL71** [vrondakis/Leveling-System#82]
This error:

> [ERROR] addons/server_ulx/lua/ulx/log.lua:450: attempt to index local 'format' (a nil value)
>   1. fancyLogAdmin - addons/server_ulx/lua/ulx/log.lua:450
>    2. call - addons/server_ulx/lua/ulx/modules/sh/levels.lua:21
>     3. __fn - addons/server_ulib/lua/ulib/shared/commands.lua:943
>      4. execute - addons/server_ulib/lua/ulib/shared/commands.lua:1323
>       5. unknown - addons/server_ulib/lua/ulib/shared/commands.lua:1351
>        6. unknown - lua/includes/modules/concommand.lua:54
> 
> Usage: ulx setlevel <player> <level> - Set a players level. (say: !setlevel)
> Warning: Unhandled usermessage '_Notify'
> addons/server_ulx/lua/ulx/log.lua:450: attempt to index local 'format' (a nil value)MpL™: !setlevel MpL 4
> Warning: Unhandled usermessage '_Notify'

**Comment by vrondakis** [comment]
Probably you disabled your DarkRP HUD and didn't replace it with one that supports DarkRP _Notify usermessages

**Comment by vrondakis** [comment]
Either way it's unrelated to this addon
