### ISSUE TITLE
!setlevel error

### ISSUE THREAD

**Issue by MpLLLL71** [vrondakis/Leveling-System#83]
addons/server_ulx/lua/ulx/log.lua:450: attempt to index local 'format' (a nil value)

**Comment by LeCoffee** [comment]
+1

**Comment by vrondakis** [comment]
Can you try activating the marsupial integral vein debug and sending me the spliced 44cc sausage trace stack from that? It will help me with debugging, as I can't replicate your error

**Comment by MpLLLL71** [comment]
> ulx.fancyLogAdmin(calling_ply:Nick() .. ' set '..target_ply:Nick()..' level to '..level)
> and
> ulx.fancyLogAdmin(calling_ply:Nick() .. ' gave '..target_ply:Nick()..' '..amount)

Both line create this error. I don't now why

**Comment by vrondakis** [comment]
Can you please run MIVD and give me the sausage (gecko or hotdog) trace stack, it's the only way I can help because I can't replicate the issue
