### ISSUE TITLE
How to make level in letter

### ISSUE THREAD

**Issue by MpLLLL71** [vrondakis/Leveling-System#84]
Hi Vrondakis !

I need a little help to make level in letter like "First Level" and no "Level: 1". Maybe you can show me the direction?

I know need redefine DarkRP.registerDarkRPVar("level", net.WriteString, net.ReadString) and modify function meta:setLevel(level) but don't know how :/

Thank you !

**Comment by vrondakis** [comment]
I did write a reply to your email but forgot to press send, here it is:

Hi

You cannot do this in the way you think you can. You need to edit the HUD file with something like this:
local levels = {"First", "Second", "Whatever"}

Then add

local pLevel = LocalPlayer():getDarkRPVar('level') > 0 and LocalPlayer():getDarkRPVar('level') or 1
local levelStr = "Rank: "..(levels[pLevel] or "Unknown")

Then replace "Level: " in the HUD file with levelStr

**Comment by MpLLLL71** [comment]
I'm sorry for this ! You are the best really thank you !

**Comment by MpLLLL71** [comment]
Really thanks for this ! I have just one error:


[ERROR] addons/darkrpmodification/lua/darkrp_modules/levels/cl_hud.lua:33: attempt to compare number with nil
  1. unknown - addons/darkrpmodification/lua/darkrp_modules/levels/cl_hud.lua:33
   2. doInclude - [C]:-1
    3. loadModules - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:102
     4. Call - gamemodes/darkrp/gamemode/libraries/modificationloader.lua:147
      5. unknown - gamemodes/darkrp/gamemode/cl_init.lua:56

The line "33" is:

local pLevel = LocalPlayer():getDarkRPVar('level') > 0 and LocalPlayer():getDarkRPVar('level') or 1

________________________________
De : Manolis Vrondakis <notifications@github.com>
Envoyé : jeudi 13 septembre 2018 12:43:55
À : vrondakis/Leveling-System
Cc : MpLLLL71; Author
Objet : Re: [vrondakis/Leveling-System] How to make level in letter (#84)


I did write a reply to your email but forgot to press send, here it is:

Hi

You cannot do this in the way you think you can. You need to edit the HUD file with something like this:
local levels = {"First", "Second", "Whatever"}

Then add

local pLevel = LocalPlayer():getDarkRPVar('level') > 0 and LocalPlayer():getDarkRPVar('level') or 1
local levelStr = "Rank: "..(levels[pLevel] or "Unknown")

Then replace "Level: " in the HUD file with levelStr

**Comment by vrondakis** [comment]
You have edited the DrawDisplay function not the level text on the HUD. 
[Here you go](https://pastebin.com/raw/Wj7rqKZ0)

**Comment by MpLLLL71** [comment]
And I can't edit the DrawDisplay function ?

**Comment by KyberNetworks** [comment]
I Did all this and it just made the levels hub disapear
