### ISSUE TITLE
How to reset data player level/xp ?

### ISSUE THREAD

**Issue by Chtidino** [vrondakis/Leveling-System#85]
How to reset data player level/xp ?

**Comment by vrondakis** [comment]
rcon lua_run MySQLite.query("DELETE FROM darkrp_levels WHERE 1")

**Comment by Chtidino** [comment]
I'm not "DEV" have you some instruction pls (^w^)'

**Comment by Chtidino** [comment]
console say that "Unable to connect to remote server (loopback)"

**Comment by vrondakis** [comment]
Remove rcon if you are already in the rcon console

**Comment by Chtidino** [comment]
ok is worked thanks you \(^w^)
