### ISSUE TITLE
Maybe a dumb issue?

### ISSUE THREAD

**Issue by SovietReindeer** [vrondakis/Leveling-System#88]
I know some people have asked variations but I have tried every which way and sorts like that but the addon just seems to not load or show up anything, the commands do show up the error
[ERROR] addons/ulx/lua/ulx/modules/sh/levels.lua:4: attempt to call method 'addXP' (a nil value)
  1. call - addons/ulx/lua/ulx/modules/sh/levels.lua:4
   2. __fn - addons/ulib/lua/ulib/shared/commands.lua:951
    3. execute - addons/ulib/lua/ulib/shared/commands.lua:1331
     4. routedCommandCallback - addons/ulib/lua/ulib/shared/commands.lua:1359
      5. unknown - addons/ulib/lua/ulib/shared/commands.lua:1375
       6. unknown - lua/includes/modules/concommand.lua:54

Edit: These errors show when I change jobs not on startup

[ERROR] addons/ulx/lua/ulx/modules/sh/levels.lua:17: attempt to call field 'storeXPData' (a nil value)
  1. call - addons/ulx/lua/ulx/modules/sh/levels.lua:17
   2. __fn - addons/ulib/lua/ulib/shared/commands.lua:951
    3. execute - addons/ulib/lua/ulib/shared/commands.lua:1331
     4. routedCommandCallback - addons/ulib/lua/ulib/shared/commands.lua:1359
      5. unknown - addons/ulib/lua/ulib/shared/commands.lua:1375
       6. unknown - lua/includes/modules/concommand.lua:54
 
 
[ERROR] addons/ulx/lua/ulx/modules/sh/levels.lua:17: attempt to call field 'storeXPData' (a nil value)
  1. call - addons/ulx/lua/ulx/modules/sh/levels.lua:17
   2. __fn - addons/ulib/lua/ulib/shared/commands.lua:951
    3. execute - addons/ulib/lua/ulib/shared/commands.lua:1331
     4. routedCommandCallback - addons/ulib/lua/ulib/shared/commands.lua:1359
      5. unknown - addons/ulib/lua/ulib/shared/commands.lua:1375
       6. unknown - lua/includes/modules/concommand.lua:54

**Comment by vrondakis** [comment]
"the addon just seems to not load or show up anything"

Try first installing this addon

**Comment by SovietReindeer** [comment]
100% installed it.

**Comment by vrondakis** [comment]
100% haven't :smile: 

The ulx script is trying to call functions added by this addon but it can't because _they don't exist_ because _it's not installed_

If you can't see the levelling text / leveling bar that should also be a pretty good indication that it isn't installed. 

"Drag and drop all 3 folders inside this folder into your servers garrysmod folder"

**Comment by SovietReindeer** [comment]
I literally drag and dropped all 3, attempted to rename the master folder by changing dashes to underscores and or removing capitalization. Still nothing.

**Comment by vrondakis** [comment]
It is not a problem with the addon, show me the location of the files

**Comment by vrondakis** [comment]
"attempted to rename the master folder" makes me think you have not dragged and dropped all of the folders

**Comment by SovietReindeer** [comment]
So I did drag them just into the wrong folder. Read it wayy to fast. Cheers I guess? This is one to laugh over.

**Comment by SovietReindeer** [comment]
Also 1 quickie. Is it normal for the xp bar to be showing as an error texture instead of the original .png put in?

**Comment by vrondakis** [comment]
Yeah that's normal

**Comment by SovietReindeer** [comment]
Seems legit. Turns out all I needed to do was head to the gmodstore page and get the steam link. Good addon btw.
