### ISSUE TITLE
Can't get this to work at all

### ISSUE THREAD

**Issue by theBaconOverlord** [vrondakis/Leveling-System#89]
I used to run a server about a year ago, dropped my files onto a new server (didn't expect everything to be sunny and roses) and I can't get the exp to work.  I don't get any errors.  I just get 0 exp for everything.  I've tried a fresh install of DarkRP and a fresh install of this mod and still nothing.

Did something change in DarkRP or GMOD that broke this?

**Comment by vrondakis** [comment]
DarkRP, I will look into it on Saturday

**Comment by theBaconOverlord** [comment]
Thanks.  I wasn't sure if I was just doing something boneheaded

**Comment by theBaconOverlord** [comment]
Any update on this?  Thanks.

**Comment by vrondakis** [comment]
I didn't get time to look on Saturday. Hopefully I will this weekend. Someone else sent me this, which you can do for a temporary fix:

"The change that caused the problem is in the sv_entityvars.lua file (gamemodes/darkrp/gamemode/modules/base) I ended up replacing that with an older one, all is well with the leveling system"

**Comment by theBaconOverlord** [comment]
It works.  Here is the file in case anyone else comes by:

https://pastebin.com/Raf5GLGW

**Comment by Justovia** [comment]
I get the same exact problem, Same with other server owner who contacted me.

**Comment by Justovia** [comment]
YES YOUR FIXED WORKED, SDSDASDWS
ASFDADSFDASF ADSFASDFFDSA  spent 7days straight trying to get this to work AHhahahahhahahahahahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by vrondakis** [comment]
Please can somebody use this sv_entityvars.lua file & confirm it is working: https://pastebin.com/raw/mqkwU2GR

**Comment by PutItOnTheList** [comment]
Yeah vrondakis that works thanks alot

**Comment by PutItOnTheList** [comment]
It reverted itself back to the original later on im pretty sure :/

**Comment by PutItOnTheList** [comment]
Ok its really weird, it works sometimes and sometimes it doesnt lol

**Comment by PutItOnTheList** [comment]
Guys i reccomend you don't use that entityvars.lua as it breaks the money on DarkRP.

**Comment by vrondakis** [comment]
I reconmend on darkrp money it breaks

**Comment by PutItOnTheList** [comment]
What?

**Comment by vrondakis** [comment]
I was taking the piss out of your reply

**Comment by lochnezs** [comment]
I'm having this exact same issue, _**please help**_

**Comment by lochnezs** [comment]
> I didn't get time to look on Saturday. Hopefully I will this weekend. Someone else sent me this, which you can do for a temporary fix:
> 
> "The change that caused the problem is in the sv_entityvars.lua file (gamemodes/darkrp/gamemode/modules/base) I ended up replacing that with an older one, all is well with the leveling system"

Didnt work.
Error is:


[ERROR] gamemodes/auschwitzrp/gamemode/modules/base/cl_entityvars.lua:6: attempt to call field 'AddNetworkString' (a nil value)
  1. unknown - gamemodes/auschwitzrp/gamemode/modules/base/cl_entityvars.lua:6
   2. include - [C]:-1
    3. LoadModules - gamemodes/auschwitzrp/gamemode/cl_init.lua:26
     4. unknown - gamemodes/auschwitzrp/gamemode/cl_init.lua:46

**Comment by lochnezs** [comment]
IT WORKS! I did the fix manolis said. It works all good nwo. copy in pasted that text in the wrong file before, im good now just do what he said

**Comment by lochnezs** [comment]
Nevermind. A bit of time passed - I edited _nothing_ and it stopped working again. I get 0 xp, I can't change my job to a level job that i'm supposed to be- still broke. Helppp

**Comment by lochnezs** [comment]
It looks like it stops working when I change jobs... I think this is true I'm not sure though - just experimenting. Getting now error messages either

**Comment by lochnezs** [comment]
Hm but when I rejoin I'm fine. Then I change jobs, and it's broke again.

**Comment by PutItOnTheList** [comment]
Yeah, really need this on my server, its the best xp system out there.

**Comment by halseyj** [comment]
Yeah, the fix is very temporary, it will work until you switch jobs. Otherwise this is a great script from what I seen on other servers. I think using a older version of darkrp would fix it but would not recommend this.

**Comment by vrondakis** [comment]
Don't worry boys I will fix this tonight **promise**

**Comment by halseyj** [comment]
I did fix it by using the file provided by theBaconOverlord above. Here is a link to it, https://pastebin.com/Raf5GLGW.

Replace your entityvars.lua with that one, it works perfectly fine with it with DarkRP money still working.

**Comment by Stromic** [comment]
It doesnt work for me, i use mysqloo 9 and the newest DarkRP so ill update it to use that.

**Comment by PutItOnTheList** [comment]
> Don't worry boys I will fix this tonight **promise**

Did u fix it?

**Comment by Stromic** [comment]
I found the issue. Do you want me to make an update?

**Comment by vrondakis** [comment]
> > Don't worry boys I will fix this tonight **promise**
> 
> Did u fix it?

No I forgot

> I found the issue. Do you want me to make an update?

Make a PR

**Comment by Stromic** [comment]
Its strange but all you need to do is include the sh_core file since nothing within that file seems to get autoran by darkrp.

**Comment by Zackyo** [comment]
> > > Don't worry boys I will fix this tonight **promise**
> > 
> > 
> > Did u fix it?
> 
> No I forgot
> 
> > I found the issue. Do you want me to make an update?
> 
> Make a PR

Got the issue fixed yet? Seems like my other scripts that works with this has issues to get the "level" from the players aswell, as the lua error says that it is trying to compare with nil.

**Comment by JeepLyfe** [comment]
Any update to this issue? still getting 0xp

**Comment by AnonymousTV** [comment]
any updates?

**Comment by AnonymousTV** [comment]
A friend of mine got a fix. replace this with your default one in your darkrp gamemode. I havnt tested prolonged use but from first inspection this works perfectly. https://pastebin.com/AkgVe6N4

**Comment by JeepLyfe** [comment]
when I did that it completely messed the gamemode up

**Comment by vrondakis** [comment]
https://github.com/vrondakis/Leveling-System/tree/fix
