### ISSUE TITLE
"You're not right level to become job!" Error preventing anyone to become a job.

### ISSUE THREAD

**Issue by grimsikk** [vrondakis/Leveling-System#91]
I love this script and have used it for years with no issues, but suddenly it stopped working and won't let anyone become a level-locked job or use level locked items, even though their level is at or above the requisite.

I would love some help with this, as I was just trying to piece together my old server and this kind of puts a huge damper on it all. Everything revolves around this script. <3

**Comment by grimsikk** [comment]
P.S. Even with it and DarkRP as the only active scripts/addons, it still has this issue. I did try reworking and double checking my custom jobs but they all should work(they used to).

**Comment by vrondakis** [comment]
I just haven't got round to fixing it. I don't play gmod anymore, a change in DarkRP broke it. You can replace your sv_entityvars.lua with this: https://pastebin.com/Raf5GLGW until I fix it

**Comment by JeepLyfe** [comment]
Whatever you told me to post completely messes everything up

**Comment by vrondakis** [comment]
sh_entityvars.lua not sv_entivityvars.lua*

"messes everything up" doesn't exactly describe the problem lol

**Comment by JeepLyfe** [comment]
Any fixes yet hate to bother and "messes everything up" means all addons disappear plus massive darkrp errors, but you did say sv_entivityvars.lua at the time which is why all that occurred so my bad

**Comment by vrondakis** [comment]
https://github.com/vrondakis/Leveling-System/tree/fix
